### ISSUE TITLE
Опиши пожалуйста основные моменты приложения

### ISSUE THREAD

**Issue by acrossoffwest** [KOVCHENKO/fias#1]

**Comment by KOVCHENKO** [comment]
Приложение предназначено для управления адресной системой. 
Отличие от существующих API сервисов:
- Возможность жесткой привязки адреса к определенным районам регионам для последующего составления отчетности.
- Наличие небольшого плагина (компоненты vue.js) для добавления новой адресной информации вручную, самим пользователем.
- Классы и методы для подтягивания GIS информации со стороннего сервиса. База данных PostgreSQL хранит информацию о точках.

Основные моменты архитектуры:
- Backend: PHP-Laravel. Несколько контроллеров для обновления БД, запроса адресов и работы с удаленными API (например, GIS API);
- Frontend-плагин -VueJs (можно вставить как компонент для выбора адреса в SPA приложение или просто как код JavaScript);
- БД - PostgreSQL.
- Основная адресная информация взята с адресной базы FIAS.
